/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chat;

import rojerusan.RSFotoSquare;

/**
 *
 * @author Monto
 */
public class Perfil extends javax.swing.JPanel {

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSFotoSquare1 = new rojerusan.RSFotoSquare();

        setBackground(new java.awt.Color(6, 35, 52));
        setForeground(new java.awt.Color(6, 35, 52));
        setPreferredSize(new java.awt.Dimension(160, 200));

        rSFotoSquare1.setBackground(new java.awt.Color(6, 35, 52));
        rSFotoSquare1.setColorBorde(new java.awt.Color(6, 35, 52));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSFotoSquare1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSFotoSquare1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public RSFotoSquare getrSFotoSquare1() {
        return rSFotoSquare1;
    }

    public void setrSFotoSquare1(RSFotoSquare rSFotoSquare1) {
        this.rSFotoSquare1 = rSFotoSquare1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSFotoSquare rSFotoSquare1;
    // End of variables declaration//GEN-END:variables
}

